name: AKS CICD

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      scale-application:
        description: "Whether to scale the application pods?"
        required: true
        default: "false"
      logs-events:
        description: "Do you need the logs?"
        required: true
        default: "false"
      

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3

      - name: Set up Azure CLI
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS}}

      - name: Setup AKS Cluster Access
        run: |
          az aks get-credentials --resource-group <resource-group-name> --name <aks-cluster-name>

      - name: Deploy Workloads
        run: |
          cd ./k8s/
          kubectl apply -f hello-world-namespace.yaml
  
      - name: Deploy Workloads
        run: |
          cd ./k8s/
          kubectl apply -f hello-world-deployment.yaml

      - name: Check Application Status
        run: |
          cd ./k8s/
          kubectl get pods -n development

      - name: Check Application Readiness
        run: |
          cd ./k8s/
          kubectl get pods -n development --field-selector=status.phase=Running

    #   - name: Perform Health Check
    #     run: |
    #       curl http:/<ip>/health

      - name: Scale Application Pods
        if: ${{ github.event_name == 'push' && github.ref == 'refs/head/main' && inputs.scale-application == 'true' }}
        run: |
          cd ./k8s/
          kubectl scale deployment hello-world --replicas=3 -n development

      - name: Pod logs and events
        if: ${{ github.event_name == 'push' && github.ref == 'refs/head/main' && inputs.logs-events == 'true' }}
        run: |
          cd ./k8s/
          kubectl get pods -n development
          kubectl logs -n development hello-world
          kubectl describe pods -n development
