name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Set up Terraform
          uses: hashicorp/setup-terraform@v3
          with:
            terraform_version: "1.1.7"

        - name: Configure Azure Credentials
          uses: azure/login@v2
          with:
            creds: ${{ secrets. AZURE_CREDENTIALS }}

        - name: Terraform Init
          run: |
            cd ./
            terraform init -backend-config=./backend/backend-dev.tfvars

        - name: Terraform Validate
          run: |
            cd .
            terraform validate

        - name: Terraform Plan
          run: |
            cd ./
            terraform plan -var-file=./tfvars/dev.tfvars

        - name: Terraform Apply
          run: |
            cd ./
            terraform apply -var-file=./tfvars/dev.tfvars -auto-approve
